### ISSUE TITLE
Abnormally high Upstash redis reads per second triggered by HTTP health checker of AWS EC2 load balancer.

### ISSUE THREAD

**Issue by waffo-js** [miurla/morphic#145]
**Describe the bug**

I have morphic deployed on both Vercel and locally on AWS. The AWS version was deployed using docker-compose, with latest commits around one week later than the Vercel one. 

And I got warning from Upstash that I've exceeded the free tier on the same day of AWS deployment, I added my credit card and found today that morphic has read 31GB of data with 1.7M reads. I shutdown the container and the reads went down to zero instantly.

The patter was highly regular and I suspected the trigger was the health check on the HTTP port, done by AWS EC2 load balancer. I turned down the frequency and the load went down as well.

I guess when everything HTTP health check reads the "/" path, the whole history is loaded and triggered many reads on Upstash.

Apart from the issue, I would highly suggest adding a local Redis option as Upstash doesn't cover global regions such as Singapore and Hong Kong.

**Screenshots**
![image](https://github.com/miurla/morphic/assets/145320594/606eba3a-f66c-4b7e-9b38-bda23b0b3df9)

![image](https://github.com/miurla/morphic/assets/145320594/9cd6d46e-8e06-48f2-8c6d-c09399a871c6)

**Comment by arsaboo** [comment]
Another vote for local redis #110

**Comment by miurla** [comment]
@waffo-js 

Thank you for the report.

The AWS EC2 Load Balancer is frequently accessing the "/" path, which may be causing a large number of data requests to Upstash. It is also possible that the cache is not working effectively. It's an abnormal number for the amount of writing.
Even morphic.sh, hosted on Vercel, is still at 12GB of bandwidth and 0.6M reads. I believe it is unlikely to exceed the free tier of Upstash with normal personal use.
Since we don't support the AWS environment, we don't know the details.

> Upstash doesn't cover global regions such as Singapore and Hong Kong.

If you choose the global type, you can select the Singapore region as well.

<img width="549" alt="image" src="https://github.com/miurla/morphic/assets/3412179/f368a911-cfab-4ba9-a49a-1e0e07d395ee">

**Comment by waffo-js** [comment]
Thanks Yoshiki. AWS is just the hosting environment, and I used docker for the deployment, nothing special.

The problem is indeed the "/" health check, which I don't think cache works in this case. Is there any other path that I can use for the health check monitoring without loading all the history?

Will check the Upstash region settings.

**Comment by waffo-js** [comment]
Yup, should be easy to fix.
