### ISSUE TITLE
Support for using Groq

### ISSUE THREAD

**Issue by itsaark** [miurla/morphic#36]
It would be awesome if you could add support for Groq!

**Comment by miurla** [comment]
Groq's speed is attractive. 
Previously, I tried Groq because it has an OpenAI-compatible API, but I gave up on it due to an error occurring midway. Either Groq's compatibility needs to improve, or we need to wait for Groq's API to support streaming for tool calling.

https://console.groq.com/docs/openai

**Comment by ndimas** [comment]
Do you have a branch with your Groq experiment? Can we somehow help you? 🥇

**Comment by miurla** [comment]
We cannot support parts that require tool calling and JSON output, but I 've made it possible to specify Groq for the final output.

https://github.com/miurla/morphic/pull/58
