### ISSUE TITLE
Can I deploy this to cloudflare？

### ISSUE THREAD

**Issue by techiewmvp** [miurla/morphic#76]
I don`t have a vercel account ，can i use cloudflare as an alternative ？If i deploy this project to pages how to set env variables？

**Comment by miurla** [comment]
I haven't tried it myself, so I'm not sure. As a requirement, Next.js/edge runtime should work on Cloudflare Pages, but it seems like additional configuration might be necessary. 
https://developers.cloudflare.com/pages/framework-guides/nextjs/deploy-a-nextjs-site/

If you just want to try it out, Vercel also has a free account, which would be easier.

**Comment by ckt1031** [comment]
You can deploy on Cloudflare, you can either fork or deploy from local machine 

For the fork, your build command should be `npx @cloudflare/next-on-pages@1`. First build must be failure, since you should set the compatibility_flag with `nodejs_compat`, after you configured it, rebuild and it will be successful.

For local machine, you should use `npx @cloudflare/next-on-pages@1`
Then, deploy it, `npx wrangler pages publish .vercel/output/static`, but you also need to config the compatibility flag.

**Comment by miurla** [comment]
Updated: https://github.com/miurla/morphic?tab=readme-ov-file#cloudflare-pages
